server:
  port: 9000

spring:
  application:
    name: GateWayMS
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-ms
              uri: lb://UserMS
              predicates:
                - Path=/api/users/**
              filters:
                - Token

            - id: profile-ms
              uri: lb://ProfileMS
              predicates:
                - Path=/profile/**
              filters:
                - Token

            - id: appointment-ms
              uri: lb://Appointment
              predicates:
                - Path=/appointment/**
              filters:
                - Token
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

jwt:
  secret: hospital-management-user-service-jwt-secret-key-256
