spring.application.name=ProfileMS
DOCTOR_ALREADY_EXISTS=Doctor already exists
PATIENT_ALREADY_EXISTS=Patient already exists
DOCTOR_NOT_FOUND=Doctor not found
PATIENT_NOT_FOUND=Patient not found


server.port = 9100
spring.datasource.url=jdbc:mysql://localhost:3306/profiledb
spring.datasource.username=root
spring.datasource.password=qutoz2274
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
